[package]
name = "kekbit-core"
version = "0.1.0"
authors = ["motoras <motoras@gmail.com>"]
edition = "2018"


[dependencies]
memmap = "0.7.0"
log = "0.4.8"


[dev-dependencies]
tempdir = "0.3.7"
simple_logger ="1.5.0"
nix="0.17.0"
crossbeam ="0.7.3"
